apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apachePhp.name }}-service
spec:
  ports:
  - port: {{ .Values.apachePhp.port }}
    targetPort: {{ .Values.apachePhp.targetPort }}
  selector:
    app: {{ .Values.apachePhp.name }}
  externalIPs:
    - {{ .Values.apachePhp.externalIPs }}
  type: {{ .Values.apachePhp.type }}
